locale: 'nl'
media_folder: "themes/mct/images" # Media files will be stored in the repo under images/uploads 
# publish_mode: editorial_workflow
# TODO: change to azure storage


backend:
    name: github
    repo: NMCT/mct-design
    branch: master # Branch to update (optional; defaults to master)


collections:
  - name: "nieuws" # Used in routes, e.g., /admin/collections/blog
    label: "Nieuws" # Used in the UI
    label_singular: "Nieuwsartikel"
    folder: "content/nieuws" # The path to the folder where the documents are stored
    slug: "{{slug}}/index{{extension}}"
    create: true # Allow users to create new documents in this collection
    fields: # The fields for each document, usually in front matter
      - {label: "Titel", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Intro", name: "description", widget: "text"}
      - {label: "Featured Image", name: "cover", widget: "image", allow_multiple: false}
      - {label: "Body", name: "body", widget: "markdown"}


