# name: MCT deployment

# env:
#   AZURE_WEBAPP_NAME: nmct    # set this to your application's name
#   AZURE_WEBAPP_PACKAGE_PATH: 'public'      # set this to the path to your web app project, defaults to the repository root

# on:
#   push:
#     branches:
#       - master

# jobs:
#   deploy:
#     runs-on: ubuntu-18.04
#     steps:
#       - uses: actions/checkout@v2
#         with:
#           submodules: true  # Fetch Hugo themes (true OR recursive)
#           fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod
    
#       - name: Setup Hugo
#         uses: peaceiris/actions-hugo@v2
#         with:
#           hugo-version: '0.81.0'
#           extended: true

#       - name: Build
#         run: hugo --minify

#       - name: Deploy to Azure WebApp
#         uses: azure/webapps-deploy@v2
#         with:
#           app-name: ${{ env.AZURE_WEBAPP_NAME }}
#           publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
#           package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
